# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0.2']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Check for Gemfile.lock updates
      run: |
        bundle install
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        if ! git diff --exit-code Gemfile.lock; then
          git add Gemfile.lock
          git commit -m "Update Gemfile.lock"
          git push
        fi
        
    - name: Run tests
      env:
        DD_CIVISIBILITY_AGENTLESS_ENABLED: 'true'
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        DD_SITE: us5.datadoghq.com
        DD_ENV: ci
      run: bundle exec rake test
